[versions]
agp = "8.2.2"
gradle = "8.2.2"
junit-junit = "4.13.2"
ktlint = "4.2.0"
kotlin = "1.9.22"
androidx-core-splashscreen = "1.0.1"
androidx-core-ktx = "1.12.0"
androidx-appcompat = "1.6.1"
com-google-android-material = "1.11.0"
androidx-constraintlayout = "2.1.4"
navigationSafeArgsGradlePlugin = "2.7.7"
androidx-navigation-fragment-ktx = "2.7.7"
androidx-navigation-ui-ktx = "2.7.7"
androidx-work-runtime-ktx = "2.9.0"
com-github-kirich1409-viewbindingpropertydelegate = "1.5.9"
dagger-hilt = "2.50"
mpandroidchart = "v3.1.0"
com-google-accompanist-permissions = "0.34.0"
com-google-dagger-hilt-android = "2.50"
com-google-dagger-hilt-compiler = "2.50"
androidx-hilt-compiler = "1.2.0"
androidx-hilt-work = "1.2.0"
safe-args = "2.7.7"
retrofit = "2.9.0"
okHttp = "4.11.0"
room = "2.6.1"
datastore = "1.0.0"
paging = "3.2.1"
firebase-analytics = "21.5.1"
firebase-config = "21.6.2"
firebase-messaging = "23.4.1"
junit = "1.1.5"
view-pager = "1.0.0"
espresso-core = "3.5.1"
lottie = "6.3.0"
dotsindicator = "5.0"


[libraries]
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "com-google-android-material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
junit = { module = "junit:junit", version.ref = "junit-junit" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }
navigation-safe-args-gradle-plugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePlugin" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation-fragment-ktx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation-ui-ktx" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work-runtime-ktx" }
viewbindingpropertydelegate = { group = "com.github.kirich1409", name = "viewbindingpropertydelegate-noreflection", version.ref = "com-github-kirich1409-viewbindingpropertydelegate" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "com-google-accompanist-permissions" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "com-google-dagger-hilt-android" }
com-google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "com-google-dagger-hilt-compiler" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt-compiler" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidx-hilt-work" }
gradle-api = {group = "com.android.tools.build", name = "gradle-api", version.ref = "gradle"}
kotlin-gradle = {group = "org.jetbrains.kotlin",name = "kotlin-gradle-plugin", version.ref = "kotlin"}
retrofit = {group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit-converter = {group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}
okHttp = {group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp" }
room = {group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler= {group = "androidx.room", name = "room-compiler", version.ref = "room" }
datastore = {group = "androidx.datastore", name = "datastore-preferences", version.ref= "datastore"}
paging = {group = "androidx.paging", name = "paging-runtime",version.ref = "paging"}
room-paging = {group = "androidx.room", name = "room-paging", version.ref = "room" }
viewpager2 = {group = "androidx.viewpager2", name = "viewpager2", version.ref = "view-pager"}
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebase-analytics" }
firebase-config = { group = "com.google.firebase", name = "firebase-config", version.ref = "firebase-config" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebase-messaging" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lottie = {group = "com.airbnb.android", name = "lottie", version.ref = "lottie"}
dotsindicator = {group = "com.tbuonomo", name = "dotsindicator", version.ref = "dotsindicator"}


[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp"}
org-jetbrains-kotlin = {id = "org.jetbrains.kotlin.android", version.ref = "kotlin"}
org-jmailen-kotlinter = { id = "org.jmailen.kotlinter", version.ref = "ktlint" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android",version.ref = "dagger-hilt" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "safe-args" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
